export const PROMOTION_STATUS_ACTIVE = 1
export const PROMOTION_STATUS_DEACTIVATE = 2
export const PROMOTION_STATUS_DRAFT = 3

export const PROMOTION_TYPE_SYSTEM = 1
export const PROMOTION_TYPE_MARKETING = 2
